[package]
name = "OS_Project"
version = "0.1.0"
edition = "2021"

[dependencies]
procfs = "0.14.0"
nix = { version = "0.29", features = ["aio", "process", "signal", "resource"] }
sysinfo = "0.32.0"
which = "7.0.0"
